trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

name: $(BuildID)-$(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if notIn(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    buildImage: false
    deployService: false
    deployEnvironment: 'no'
    imageTags: 'no'
    apiServiceName: 'no'
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    buildImage: true
    deployService: true
    deployEnvironment: 'production'
    imageTags: |
      $(Build.BuildId)
      latest
    apiServiceName: 'arkopong_api'

stages:
- stage: build
  displayName: build
  jobs:
  - job: build_api
    steps:
    - pwsh: ./build.ps1
    - publish: deploy
      artifact: arkopong-api-build
